// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lemon-cloud-user-common/dto/enroll_dto.proto

package dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInByNumberReq struct {
	ClientInfo           *ClientInfo `protobuf:"bytes,1,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	Number               string      `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Password             string      `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SignInByNumberReq) Reset()         { *m = SignInByNumberReq{} }
func (m *SignInByNumberReq) String() string { return proto.CompactTextString(m) }
func (*SignInByNumberReq) ProtoMessage()    {}
func (*SignInByNumberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f514b067056196da, []int{0}
}

func (m *SignInByNumberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInByNumberReq.Unmarshal(m, b)
}
func (m *SignInByNumberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInByNumberReq.Marshal(b, m, deterministic)
}
func (m *SignInByNumberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInByNumberReq.Merge(m, src)
}
func (m *SignInByNumberReq) XXX_Size() int {
	return xxx_messageInfo_SignInByNumberReq.Size(m)
}
func (m *SignInByNumberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInByNumberReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignInByNumberReq proto.InternalMessageInfo

func (m *SignInByNumberReq) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

func (m *SignInByNumberReq) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *SignInByNumberReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInByWeChatReq struct {
	ClientInfo           *ClientInfo `protobuf:"bytes,1,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	Code                 string      `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SignInByWeChatReq) Reset()         { *m = SignInByWeChatReq{} }
func (m *SignInByWeChatReq) String() string { return proto.CompactTextString(m) }
func (*SignInByWeChatReq) ProtoMessage()    {}
func (*SignInByWeChatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f514b067056196da, []int{1}
}

func (m *SignInByWeChatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInByWeChatReq.Unmarshal(m, b)
}
func (m *SignInByWeChatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInByWeChatReq.Marshal(b, m, deterministic)
}
func (m *SignInByWeChatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInByWeChatReq.Merge(m, src)
}
func (m *SignInByWeChatReq) XXX_Size() int {
	return xxx_messageInfo_SignInByWeChatReq.Size(m)
}
func (m *SignInByWeChatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInByWeChatReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignInByWeChatReq proto.InternalMessageInfo

func (m *SignInByWeChatReq) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

func (m *SignInByWeChatReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SignInRsp struct {
	ServiceInfo          *ServiceInfo `protobuf:"bytes,1,opt,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
	Token                string       `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpiredAt            int32        `protobuf:"varint,3,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SignInRsp) Reset()         { *m = SignInRsp{} }
func (m *SignInRsp) String() string { return proto.CompactTextString(m) }
func (*SignInRsp) ProtoMessage()    {}
func (*SignInRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f514b067056196da, []int{2}
}

func (m *SignInRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRsp.Unmarshal(m, b)
}
func (m *SignInRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRsp.Marshal(b, m, deterministic)
}
func (m *SignInRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRsp.Merge(m, src)
}
func (m *SignInRsp) XXX_Size() int {
	return xxx_messageInfo_SignInRsp.Size(m)
}
func (m *SignInRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRsp proto.InternalMessageInfo

func (m *SignInRsp) GetServiceInfo() *ServiceInfo {
	if m != nil {
		return m.ServiceInfo
	}
	return nil
}

func (m *SignInRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SignInRsp) GetExpiredAt() int32 {
	if m != nil {
		return m.ExpiredAt
	}
	return 0
}

func init() {
	proto.RegisterType((*SignInByNumberReq)(nil), "dto.SignInByNumberReq")
	proto.RegisterType((*SignInByWeChatReq)(nil), "dto.SignInByWeChatReq")
	proto.RegisterType((*SignInRsp)(nil), "dto.SignInRsp")
}

func init() {
	proto.RegisterFile("lemon-cloud-user-common/dto/enroll_dto.proto", fileDescriptor_f514b067056196da)
}

var fileDescriptor_f514b067056196da = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xe9, 0xbf, 0xff, 0x16, 0x3b, 0x15, 0xd4, 0x45, 0x24, 0x14, 0x84, 0x92, 0x53, 0x0f,
	0x26, 0x11, 0xfb, 0x09, 0x6c, 0x4f, 0x45, 0xf4, 0x90, 0x1e, 0x44, 0x2f, 0x21, 0xd9, 0x9d, 0xa6,
	0x8b, 0xc9, 0x4e, 0xdc, 0xdd, 0xa8, 0xfd, 0xf6, 0xe2, 0x26, 0xb4, 0xc1, 0x43, 0x0f, 0xde, 0xe6,
	0xcd, 0xf0, 0x7e, 0x8f, 0xe1, 0xc1, 0x4d, 0x81, 0x25, 0xa9, 0x80, 0x17, 0x54, 0x8b, 0xa0, 0x36,
	0xa8, 0x03, 0x4e, 0x65, 0x49, 0x2a, 0x12, 0x96, 0x22, 0x54, 0x9a, 0x8a, 0x22, 0x11, 0x96, 0xc2,
	0x4a, 0x93, 0x25, 0xd6, 0x17, 0x96, 0x26, 0xc1, 0x31, 0x4b, 0x8e, 0x0a, 0x75, 0xda, 0xf1, 0xf8,
	0x3b, 0xb8, 0x58, 0xcb, 0x5c, 0xad, 0xd4, 0x62, 0xf7, 0x54, 0x97, 0x19, 0xea, 0x18, 0xdf, 0xd9,
	0x2d, 0x8c, 0x79, 0x21, 0x51, 0xd9, 0x44, 0xaa, 0x0d, 0x79, 0xbd, 0x69, 0x6f, 0x36, 0xbe, 0x3b,
	0x0b, 0x7f, 0x5c, 0x4b, 0xb7, 0x5f, 0xa9, 0x0d, 0xc5, 0xc0, 0xf7, 0x33, 0xbb, 0x82, 0xa1, 0x72,
	0x76, 0xef, 0xdf, 0xb4, 0x37, 0x1b, 0xc5, 0xad, 0x62, 0x13, 0x38, 0xa9, 0x52, 0x63, 0x3e, 0x49,
	0x0b, 0xaf, 0xef, 0x2e, 0x7b, 0xed, 0xbf, 0x1c, 0xa2, 0x9f, 0x71, 0xb9, 0x4d, 0xed, 0xdf, 0xa2,
	0x19, 0xfc, 0xe7, 0x24, 0xb0, 0x0d, 0x76, 0xb3, 0x5f, 0xc3, 0xa8, 0x41, 0xc7, 0xa6, 0x62, 0x73,
	0x38, 0x35, 0xa8, 0x3f, 0x24, 0xc7, 0x2e, 0xf3, 0xdc, 0x31, 0xd7, 0xcd, 0xc1, 0x41, 0xc7, 0xe6,
	0x20, 0xd8, 0x25, 0x0c, 0x2c, 0xbd, 0xa1, 0x6a, 0xb1, 0x8d, 0x60, 0xd7, 0x00, 0xf8, 0x55, 0x49,
	0x8d, 0x22, 0x49, 0xad, 0x7b, 0x68, 0x10, 0x8f, 0xda, 0xcd, 0xbd, 0x5d, 0x3c, 0xbe, 0x3e, 0xe4,
	0xd2, 0x6e, 0xeb, 0x2c, 0xe4, 0x54, 0x46, 0xdd, 0x22, 0x5a, 0x74, 0xf4, 0xbb, 0x9c, 0xe8, 0x48,
	0x5b, 0xd9, 0xd0, 0x55, 0x34, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x13, 0xb9, 0x5c, 0x75, 0x06,
	0x02, 0x00, 0x00,
}
