// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dto/enroll_dto.proto

package dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginByNumberReq struct {
	ClientInfo           *ClientInfo `protobuf:"bytes,1,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	Number               string      `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Password             string      `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginByNumberReq) Reset()         { *m = LoginByNumberReq{} }
func (m *LoginByNumberReq) String() string { return proto.CompactTextString(m) }
func (*LoginByNumberReq) ProtoMessage()    {}
func (*LoginByNumberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7167e2393f4f97e9, []int{0}
}

func (m *LoginByNumberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginByNumberReq.Unmarshal(m, b)
}
func (m *LoginByNumberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginByNumberReq.Marshal(b, m, deterministic)
}
func (m *LoginByNumberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginByNumberReq.Merge(m, src)
}
func (m *LoginByNumberReq) XXX_Size() int {
	return xxx_messageInfo_LoginByNumberReq.Size(m)
}
func (m *LoginByNumberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginByNumberReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginByNumberReq proto.InternalMessageInfo

func (m *LoginByNumberReq) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

func (m *LoginByNumberReq) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *LoginByNumberReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginByWeChatReq struct {
	ClientInfo           *ClientInfo `protobuf:"bytes,1,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	Code                 string      `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginByWeChatReq) Reset()         { *m = LoginByWeChatReq{} }
func (m *LoginByWeChatReq) String() string { return proto.CompactTextString(m) }
func (*LoginByWeChatReq) ProtoMessage()    {}
func (*LoginByWeChatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7167e2393f4f97e9, []int{1}
}

func (m *LoginByWeChatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginByWeChatReq.Unmarshal(m, b)
}
func (m *LoginByWeChatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginByWeChatReq.Marshal(b, m, deterministic)
}
func (m *LoginByWeChatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginByWeChatReq.Merge(m, src)
}
func (m *LoginByWeChatReq) XXX_Size() int {
	return xxx_messageInfo_LoginByWeChatReq.Size(m)
}
func (m *LoginByWeChatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginByWeChatReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginByWeChatReq proto.InternalMessageInfo

func (m *LoginByWeChatReq) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

func (m *LoginByWeChatReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type LoginRsp struct {
	ServiceInfo          *ServiceInfo `protobuf:"bytes,1,opt,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
	Token                string       `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpiredAt            int32        `protobuf:"varint,3,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginRsp) Reset()         { *m = LoginRsp{} }
func (m *LoginRsp) String() string { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()    {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7167e2393f4f97e9, []int{2}
}

func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsp.Unmarshal(m, b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
}
func (m *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(m, src)
}
func (m *LoginRsp) XXX_Size() int {
	return xxx_messageInfo_LoginRsp.Size(m)
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetServiceInfo() *ServiceInfo {
	if m != nil {
		return m.ServiceInfo
	}
	return nil
}

func (m *LoginRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginRsp) GetExpiredAt() int32 {
	if m != nil {
		return m.ExpiredAt
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginByNumberReq)(nil), "dto.LoginByNumberReq")
	proto.RegisterType((*LoginByWeChatReq)(nil), "dto.LoginByWeChatReq")
	proto.RegisterType((*LoginRsp)(nil), "dto.LoginRsp")
}

func init() { proto.RegisterFile("dto/enroll_dto.proto", fileDescriptor_7167e2393f4f97e9) }

var fileDescriptor_7167e2393f4f97e9 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x4e, 0xf2, 0x40,
	0x14, 0xc5, 0xc3, 0xc7, 0x07, 0x81, 0x8b, 0x89, 0x64, 0x82, 0x86, 0x90, 0x98, 0x10, 0x56, 0x6c,
	0x68, 0x8d, 0x3c, 0x81, 0xb0, 0x32, 0xfe, 0x59, 0xd4, 0x85, 0xc6, 0x4d, 0xd3, 0xce, 0x5c, 0xca,
	0xc4, 0x76, 0x6e, 0x9d, 0xb9, 0x55, 0x7c, 0x7b, 0xc3, 0xd0, 0x54, 0x8c, 0x3b, 0x77, 0xf7, 0x9c,
	0x93, 0xf3, 0x3b, 0x99, 0x0c, 0x8c, 0x14, 0x53, 0x88, 0xc6, 0x52, 0x9e, 0xc7, 0x8a, 0x29, 0x28,
	0x2d, 0x31, 0x89, 0xb6, 0x62, 0x9a, 0x9c, 0xed, 0xa3, 0x0c, 0x0d, 0xda, 0xe4, 0x28, 0x9b, 0xed,
	0x60, 0x78, 0x47, 0x99, 0x36, 0xab, 0xcf, 0x87, 0xaa, 0x48, 0xd1, 0x46, 0xf8, 0x26, 0x2e, 0x61,
	0x20, 0x73, 0x8d, 0x86, 0x63, 0x6d, 0x36, 0x34, 0x6e, 0x4d, 0x5b, 0xf3, 0xc1, 0xd5, 0x69, 0xb0,
	0x2f, 0xad, 0xbd, 0x7f, 0x63, 0x36, 0x14, 0x81, 0x6c, 0x6e, 0x71, 0x0e, 0x5d, 0xe3, 0xeb, 0xe3,
	0x7f, 0xd3, 0xd6, 0xbc, 0x1f, 0xd5, 0x4a, 0x4c, 0xa0, 0x57, 0x26, 0xce, 0x7d, 0x90, 0x55, 0xe3,
	0xb6, 0x4f, 0x1a, 0x3d, 0x7b, 0x6e, 0x96, 0x9f, 0x70, 0xbd, 0x4d, 0xf8, 0x6f, 0xcb, 0x02, 0xfe,
	0x4b, 0x52, 0x58, 0xef, 0xfa, 0x7b, 0xc6, 0xd0, 0xf3, 0xe4, 0xc8, 0x95, 0x62, 0x09, 0x27, 0x0e,
	0xed, 0xbb, 0x96, 0x78, 0x8c, 0x1c, 0x7a, 0xe4, 0xe3, 0x21, 0xf0, 0xcc, 0x81, 0xfb, 0x16, 0x62,
	0x04, 0x1d, 0xa6, 0x57, 0x34, 0x35, 0xf5, 0x20, 0xc4, 0x05, 0x00, 0xee, 0x4a, 0x6d, 0x51, 0xc5,
	0x09, 0xfb, 0xe7, 0x74, 0xa2, 0x7e, 0xed, 0x5c, 0xf3, 0xea, 0xfe, 0xe5, 0x36, 0xd3, 0xbc, 0xad,
	0xd2, 0x40, 0x52, 0x11, 0xe6, 0x58, 0x90, 0x59, 0xc8, 0x9c, 0x2a, 0xb5, 0xa8, 0xd1, 0x3f, 0xbc,
	0xca, 0xa1, 0xfd, 0x65, 0x2c, 0x24, 0x15, 0x05, 0x99, 0x50, 0x31, 0xa5, 0x5d, 0xff, 0x3f, 0xcb,
	0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x6d, 0x8e, 0x07, 0xd3, 0x01, 0x00, 0x00,
}
