// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lemon-cloud-user-common/dto/general_dto.proto

package lemon_cloud_user_common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientInfo struct {
	DeviceId             string   `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SystemInfo           string   `protobuf:"bytes,2,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AppVersion           string   `protobuf:"bytes,4,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	ExpectedApiVersion   string   `protobuf:"bytes,5,opt,name=expected_api_version,json=expectedApiVersion,proto3" json:"expected_api_version,omitempty"`
	ExpectedResponseLang string   `protobuf:"bytes,6,opt,name=expected_response_lang,json=expectedResponseLang,proto3" json:"expected_response_lang,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca9017033990cf48, []int{0}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *ClientInfo) GetSystemInfo() string {
	if m != nil {
		return m.SystemInfo
	}
	return ""
}

func (m *ClientInfo) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *ClientInfo) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *ClientInfo) GetExpectedApiVersion() string {
	if m != nil {
		return m.ExpectedApiVersion
	}
	return ""
}

func (m *ClientInfo) GetExpectedResponseLang() string {
	if m != nil {
		return m.ExpectedResponseLang
	}
	return ""
}

type ServiceInfo struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ApiVersion           string   `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrCode              int32    `protobuf:"varint,4,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,5,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca9017033990cf48, []int{1}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *ServiceInfo) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *ServiceInfo) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ServiceInfo) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ServiceInfo) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*ClientInfo)(nil), "dto.ClientInfo")
	proto.RegisterType((*ServiceInfo)(nil), "dto.ServiceInfo")
}

func init() {
	proto.RegisterFile("lemon-cloud-user-common/dto/general_dto.proto", fileDescriptor_ca9017033990cf48)
}

var fileDescriptor_ca9017033990cf48 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x99, 0xd6, 0xfe, 0xa5, 0xbb, 0x20, 0x3a, 0xa2, 0xa0, 0x74, 0xe5, 0x66, 0x3a, 0x82,
	0xbe, 0x80, 0x76, 0x21, 0x05, 0xdd, 0x8c, 0xe0, 0xc2, 0x4d, 0x48, 0x93, 0xdb, 0x31, 0x30, 0xc9,
	0x0d, 0x49, 0xa6, 0xe8, 0xab, 0xf8, 0x96, 0xbe, 0x81, 0x34, 0xd3, 0x99, 0x8a, 0x3f, 0xbb, 0x99,
	0x73, 0xee, 0x09, 0xdf, 0xe1, 0x90, 0xac, 0x02, 0x8d, 0x26, 0x13, 0x15, 0xd6, 0x32, 0xab, 0x3d,
	0xb8, 0x4c, 0xa0, 0xd6, 0x68, 0x72, 0x19, 0x30, 0x2f, 0xc1, 0x80, 0xe3, 0x15, 0x93, 0x01, 0xe7,
	0xd6, 0x61, 0x40, 0xda, 0x97, 0x01, 0x67, 0x9f, 0x09, 0x21, 0x8b, 0x4a, 0x81, 0x09, 0x4b, 0xb3,
	0x46, 0x7a, 0x4a, 0x26, 0x12, 0x36, 0x4a, 0x00, 0x53, 0x32, 0x4d, 0x2e, 0x92, 0xcb, 0x49, 0x31,
	0x6e, 0x84, 0xa5, 0xa4, 0xe7, 0x64, 0xea, 0xdf, 0x7d, 0x00, 0xcd, 0x94, 0x59, 0x63, 0xda, 0x8b,
	0x36, 0x69, 0xa4, 0x98, 0x3e, 0x23, 0x93, 0xa0, 0x34, 0xf8, 0xc0, 0xb5, 0x4d, 0xfb, 0xd1, 0xde,
	0x0b, 0xdb, 0x38, 0xb7, 0x96, 0x6d, 0xc0, 0x79, 0x85, 0x26, 0x3d, 0x68, 0xe2, 0xdc, 0xda, 0xe7,
	0x46, 0xa1, 0x57, 0xe4, 0x10, 0xde, 0x2c, 0x88, 0x00, 0x92, 0x71, 0xab, 0xba, 0xcb, 0x41, 0xbc,
	0xa4, 0xad, 0x77, 0x6b, 0x55, 0x9b, 0xb8, 0x21, 0x47, 0x5d, 0xc2, 0x81, 0xb7, 0x68, 0x3c, 0xb0,
	0x8a, 0x9b, 0x32, 0x1d, 0xc6, 0x4c, 0xf7, 0x5e, 0xb1, 0x33, 0x1f, 0xb8, 0x29, 0x67, 0x1f, 0x09,
	0x99, 0x3e, 0x81, 0x8b, 0xad, 0x7e, 0x61, 0x27, 0x7f, 0x62, 0xef, 0x61, 0x7a, 0x2d, 0x76, 0x07,
	0x91, 0x92, 0x91, 0xaf, 0x85, 0x00, 0xef, 0x63, 0xe7, 0x71, 0xd1, 0xfe, 0xd2, 0x13, 0x32, 0x06,
	0xe7, 0x98, 0x40, 0x09, 0xb1, 0xee, 0xa0, 0x18, 0x81, 0x73, 0x0b, 0x94, 0x40, 0x8f, 0xc9, 0xf6,
	0x93, 0x69, 0x5f, 0xee, 0xea, 0x0d, 0xc1, 0xb9, 0x47, 0x5f, 0xde, 0x2d, 0x5f, 0xee, 0x4b, 0x15,
	0x5e, 0xeb, 0xd5, 0x5c, 0xa0, 0xce, 0xbf, 0x2f, 0xea, 0x1b, 0xe4, 0xfc, 0xe7, 0xca, 0xf9, 0x3f,
	0xb3, 0xaf, 0x86, 0x71, 0xe7, 0xeb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x90, 0x23, 0x9b,
	0x18, 0x02, 0x00, 0x00,
}
